#!/bin/bash

pd1=~/Pictures/wallpapers/default.png
pd2=~/Pictures/wallpapers/default.jpg
if [[ -e $pd1 ]]; then
    feh --bg-fill --no-fehbg $pd1
elif [[ -e $pd2 ]]; then
    feh --bg-fill --no-fehbg $pd2
else
    dwm-changewallpaper
fi
