#!/bin/bash

killall -q picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --experimental-backends -b
# sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"
pkexec sh -c "echo 3 > /proc/sys/vm/drop_caches"
