#!/bin/bash

# 关闭enternotify
dwmc setenternotify 0

# 获取dwm monitor并转为rofi monitor
dwm_mon_num=$(cat ~/.cache/dwm/status/monitor)
mon=$(rofi -h | grep -w -B 1 "$(xrandr --listactivemonitors | tail +2 | sed -E 's/ *([0-9]+): +[^ ]+ +[^ ]+ +([^ ]+)/\1 \2/' | grep -E "^$dwm_mon_num" | cut -d ' ' -f 2)" | head -1 | sed -E 's/.*([0-9]+).*/\1/')

# 执行rofi
if [[ "$mon" =~ ^[0-9]+$ ]]; then
    rofi -m $mon "$@"
else
    rofi "$@"
fi
# 保存rofi执行结果
roficode=$?

# 重新打开enternotify
dwmc setenternotify 1

# 返回rofi执行结果
exit $roficode
