#!/bin/bash

winid=$1

killclientwin=' 󰅗 Kill Client'
togglefullscrwin=' 󰊓 Toggle Fullscreen'
togglehide='  Toggle Hide'

selection=$(
cat << EOF | xmenu
$killclientwin
$togglefullscrwin
$togglehide
EOF
)

case $selection in
    $killclientwin)
        dwmc killclientwin $winid
        ;;
    $togglefullscrwin)
        dwmc togglefullscrwin $winid
        ;;
    $togglehide)
        dwmc togglehide $winid
        ;;
esac
