#!/bin/bash

newterminal='  New Terminal'
newbrowser=' 󰊯 New Browser'
idea='  IDEA'
popo=' 﫢 POPO'
work=' 󰬱 Work'
xiaoyi=' 嬨 XiaoYi'
musicvpn=' 嬨 Music VPN'
monitor1=' 󰍹 Monitor1'
monitor2=' 󰍺 Monitor2'
gapsmall=' 󰢤 Gap Small'
gapmiddle=' 󰢤 Gap Middle'
gaplarge=' 󰢤 Gap Large'
changewallpaper=' 󰸉 Change Wallpaper'
flameshot='  Flameshot'
flameshotocr='  Flameshot OCR'
flameshotqr='  Flameshot QR'
pickcolor='  Pick Color'
togglesmartgap=' 󰃈 Toggle Smart Gap'
toggletouchpad=' 󰹟 Toggle Touchpad'
connectgalaxybus='  Connect GalaxyBus '
lockscreen='  Lock Screen'
clearcache=' 󰃨 Clear Cache'
showall='  Show All'
quitdwm=' 󰿅 Quit DWM'
reboot='  Reboot'
shutdown='  Shutdown Now'

selection=$(
cat << EOF | xmenu
$newterminal
$newbrowser
$idea
$popo
$work
$xiaoyi
$musicvpn
$monitor1
$monitor2
$gapsmall
$gapmiddle
$gaplarge
$changewallpaper
$flameshot
$flameshotocr
$flameshotqr
$pickcolor
$togglesmartgap
$toggletouchpad
$connectgalaxybus
$lockscreen
$clearcache
$showall
$quitdwm
$reboot
$shutdown
EOF
)

case $selection in
    $newterminal)
        exec dwm-termcmd
        ;;
    $newbrowser)
        exec google-chrome-stable
        ;;
    $idea)
        exec intellij-idea-ultimate-edition
        ;;
    $popo)
        exec /opt/apps/popo/files/Elevator.sh
        ;;
    $work)
        exec st bash -c 'cd /home/fengwk/Documents/work && nvim'
        ;;
    $xiaoyi)
        exec xiaoyi
        ;;
    $musicvpn)
        musicvpn-st
        ;;
    $monitor1)
        dwm-switchmonitor 1
        ;;
    $monitor2)
        dwm-switchmonitor 2
        ;;
    $gapsmall)
        dwmc setgappx 15
        ;;
    $gapmiddle)
        dwmc setgappx 25
        ;;
    $gaplarge)
        dwmc setgappx 50
        ;;
    $changewallpaper)
        dwm-changewallpaper
        ;;
    $flameshot)
        dwm-flameshot gui
        ;;
    $flameshotocr)
        dwm-flameshotocr
        ;;
    $flameshotqr)
        dwm-flameshotqr
        ;;
    $pickcolor)
        dwm-pickcolor
        ;;
    $togglesmartgap)
        dwmc togglesmartgap
        ;;
    $toggletouchpad)
        dwm-toggletouchpad
        ;;
    $connectgalaxybus)
        bluetoothctl connect $(bluetoothctl devices | grep Galaxy | awk '{print $2}')
        ;;
    $lockscreen)
        slock
        ;;
    $clearcache)
        dwm-clearcache
        ;;
    $showall)
        dwmc showall
        ;;
    $quitdwm)
        dwmc quit
        ;;
    $reboot)
        reboot
        ;;
    $shutdown)
        shutdown now
        ;;
esac
